
spring:
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/hackathon?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 1
    maxActive: 2
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'ZTM' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

#    mvc:
#        view:
#          prefix: /WEB-INF/views/
#          suffix: .jsp

mybatis:
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: com.kry.entity
  configLocation: classpath:/mybatis-config.xml


